name: navtern
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.2.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  http: ^1.1.2
  webview_flutter: ^4.4.3
  path_provider: ^2.1.1
  google_nav_bar: ^5.0.6
  material_floating_search_bar_2: ^0.5.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  material_design_icons_flutter: ^7.0.7296
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.12.1
  flutter_slider_drawer: ^2.1.3
  animated_text_kit: ^4.2.2
  provider: ^6.1.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-Medium
        weight: 500
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600