// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUC6XbMwUJr7ovG_6Uxip0akD9wRmspl4',
    appId: '1:258422529007:web:c9278ed5733600d9f1741a',
    messagingSenderId: '258422529007',
    projectId: 'navtern-c65e9',
    authDomain: 'navtern-c65e9.firebaseapp.com',
    storageBucket: 'navtern-c65e9.appspot.com',
    measurementId: 'G-85NVT1PM7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq-GkihH6tGT6QYUND_d3WyZ3LT6TPwA0',
    appId: '1:258422529007:android:3bde7d0f0cab9a6cf1741a',
    messagingSenderId: '258422529007',
    projectId: 'navtern-c65e9',
    storageBucket: 'navtern-c65e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANv0CZ7dXB9rnuWUaLoypK0L7UVFdPYVs',
    appId: '1:258422529007:ios:3ef76c451d0ffabef1741a',
    messagingSenderId: '258422529007',
    projectId: 'navtern-c65e9',
    storageBucket: 'navtern-c65e9.appspot.com',
    iosBundleId: 'com.example.navtern',
  );
}
